'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Cervezas
    Public Property id As Integer
    Public Property desc As String
    Public Property fk_levadura As Integer
    Public Property descrip As String

    Public Overridable Property Levaduras As Levaduras
    Public Overridable Property Detalles_pedidos As ICollection(Of Detalles_pedidos) = New HashSet(Of Detalles_pedidos)
    Public Overridable Property Lupulos As ICollection(Of Lupulos) = New HashSet(Of Lupulos)
    Public Overridable Property Maltas As ICollection(Of Maltas) = New HashSet(Of Maltas)
    Public Overridable Property Ins_varios As ICollection(Of Ins_varios) = New HashSet(Of Ins_varios)

End Class
