'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Cliente
    Public Property id As Integer
    Public Property nomyap As String
    Public Property telefono As Long

    Public Overridable Property Pedidos As ICollection(Of Pedidos) = New HashSet(Of Pedidos)

End Class
