'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Detalles_pedidos
    Public Property fk_pedido As Integer
    Public Property fk_cerveza As Integer
    Public Property precio_unidad As Double
    Public Property descuento As Double

    Public Overridable Property Cervezas As Cervezas
    Public Overridable Property Pedidos As Pedidos

End Class
