'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Flete
    Public Property id As Integer
    Public Property desc As String
    Public Property costo As Double
    Public Property fk_botella As Integer
    Public Property descrip As String

    Public Overridable Property Botellas As Botellas

End Class
