'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Gastos_nombres
    Public Property id As Integer
    Public Property desc As String
    Public Property descrip As String

    Public Overridable Property Gastos As ICollection(Of Gastos) = New HashSet(Of Gastos)

End Class
