'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Gastos
    Public Property id As Integer
    Public Property fecha_ini As Date
    Public Property esmensual As Boolean
    Public Property monto As Double
    Public Property desc As String
    Public Property fk_nombre As Integer
    Public Property descrip As String

    Public Overridable Property Gastos_nombres As Gastos_nombres

End Class
