'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Lupulos
    Public Property id As Integer
    Public Property desc As String
    Public Property precio_kg As Double
    Public Property descrip As String

    Public Overridable Property Cervezas As ICollection(Of Cervezas) = New HashSet(Of Cervezas)

End Class
