'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Pedidos
    Public Property id As Integer
    Public Property fecha_pedido As Date
    Public Property fecha_envio As Date
    Public Property forma_envio As String
    Public Property cargo_total As Double
    Public Property direccion_dest As String
    Public Property fk_cliente As Integer

    Public Overridable Property Cliente As Cliente
    Public Overridable Property Detalles_pedidos As ICollection(Of Detalles_pedidos) = New HashSet(Of Detalles_pedidos)

End Class
